#! /bin/sh

##### Scripts #####

nitrogen --restore	# set wallpaper
numlockx on		# turn on numlock automatically
sxhkd &			# turn on sxhkd shortcuts
#panel &			# turn on the main panel (lemonbar)
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &	# turn on the polkit agent
nm-applet &

# start xfce4 panel
xfce4-panel --disable-wm-check &

xfce4-clipman &		# start xfce4 panel plugins
pamac-tray &		# turn on pacman manager tray icon
steam -silent &
google-musicmanager &

##### BSPWM #####
bspc config border_width          2
bspc config window_gap            3

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer false
bspc config apply_shadow_property true
bspc config click_to_focus        true

##bspc monitor MONITOR02 -d 1 2 3
##bspc monitor MONITOR01 -d 4 5 6 7
##bspc monitor MONITOR03 -d 8 9 0
#bspc monitor MONITOR02 -d 1 2 3 4 5
#bspc monitor MONITOR01 -d 6 7 8 9 0
if [[ $(hostname) == 'mars' ]]; then
	bspc monitor HDMI-0 -d 1 2 3 4 5
	bspc monitor DVI-D-0 -d 6 7 8 9 0
elif [[ $(hostname) == 'phobos' ]]; then
	bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 0
fi

#### intel monitor - another wm (i3) ####
# DISPLAY=:0.1 i3 &

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a steam state=floating
bspc rule -a irccloud desktop=^1
bspc rule -a teamspeak3 desktop=^1
bspc rule -a discord desktop=^1
bspc rule -a messengerfordesktop desktop=^1

bspc config top_padding 16
#bspc config bottom_padding 3

/opt/messengerfordesktop/messengerfordesktop &
#teamspeak3 &
transmission-gtk -m &
#irccloud &

# Discord
discord &

# Shutter
shutter --min_at_startup &

# Wine Boot
wineboot -u &
